apiVersion: v1
kind: Namespace
metadata:
  name: oe 
  labels:
    bb: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: oe 
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web 
    spec:
      containers:
      - name: website 
        image: localhost:32000/oe/website:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website 
  namespace: oe 
spec:
  type: NodePort
  selector:
    bb: web 
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress 
  namespace: oe
  annotations:
    kubernetes.io/ingress.class: public 
spec:
  rules:
  - host: "www.obliteratedentertainment.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website 
            port:
              number: 80
  - host: "obliteratedentertainment.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website 
            port:
              number: 80
